(define (problem blocks1)
    (:domain blocks)
    (:objects A B C)
    (:init  (ontable A)
            (ontable B)
            (ontable C)
            (clear A)
            (clear B)
            (clear C)
            (handempty)
    )
    (:goal  (and
                (on B C)
                (on A B)
            )
    )
)