(define (problem blocks1)
    (:domain blocks)
    (:objects C D E F B I J A N O K M P H G L Q - block)
    (:init  (ontable A) (clear A)
            (ontable B) (clear B)
            (ontable C) (clear C)
            (ontable D) (clear D)
            (ontable E) (clear E)
            (ontable F) (clear F)
            (ontable G) (clear G)
            (ontable H) (clear H)
            (ontable I) (clear I)
            (ontable J) (clear J)
            (ontable K) (clear K)
            (ontable L) (clear L)
            (ontable M) (clear M)
            (ontable N) (clear N)
            (ontable O) (clear O)
            (ontable P) (clear P)
            (ontable Q) (clear Q)
            (handempty)
    )
    (:goal  (and (on Q N) (on N L) (on L O) (on O J) (on J H) (on H C) (on C E)
                 (on E M) (on M P) (on P A) (on A G) (on G B) (on B I) (on I K)
                 (on K F) (on F D))
    )
)